### ISSUE TITLE
Add pending events notification to top bar

### ISSUE THREAD

**Issue by BenGHolmes** [ubyssey/dispatch#731]
We want to display the number of pending events next to the events tab in the menu bar.

**Comment by psiemens** [comment]
@BenGHolmes here are some steps to get started with the Redux architecture. If you have time, I'd recommend reading more about Redux [here](http://redux.js.org/).

- The global state of the application (called the "store") can only be mutated through an **action**. We already have an action that fetches the number of pending events, [defined here](https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/actions/EventsActions.js#L24-L30). Calling that action will make an API request to the server and update the store with the results.
- We want to call the `countPending` action from inside [MainContainer](https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/containers/MainContainer.js). The action should be called from the `componentDidMount` method, right after [this line](https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/containers/MainContainer.js). *Note: you'll have to link `countPending` to `MainContainer`, similar to how the `setupToaster` is linked.*
- Now the store will be updated with the latest pending event count every time a page is loaded. In order to read the count from the store, we have to add a line to [this function](https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/containers/MainContainer.js#L39-L44) that looks like this:

```js
events: state.app.events
```
This plucks the `events` portion of the store, which is simply an object containing all the application data related to events. To access this object inside `MainContainer`, you can now use `this.props.events`.
- Next, we need to pass some data to the `<Header />` component on [this line](https://github.com/ubyssey/dispatch/blob/develop/dispatch/static/manager/src/js/containers/MainContainer.js#L31). I'll let you figure out how to do that, but here are some hints:
  - The pending event count is stored as an integer at `this.props.events.pending`. Its default value is `0`
  - If the pending count is `0`, the badge should not be rendered.

**Comment by psiemens** [comment]
Implemented by @BenGHolmes
